### ISSUE TITLE
Wireless device disappeared after recent update

### ISSUE THREAD

**Issue by bugthing** [ublue-os/main#244] opened 2023-06-08 08:48 UTC
hello, after a recent update of bluefin my wifi device has disappeared. If I boot into an older image the device is there, so I assume the problem is software related.
I dont know, but a recent change added akmods layer to the image, perhaps this is causing my issue. Sounds like it now includes the `wl` driver, which I assume was not there before, so I must have been using in-kernel drivers :shrug: 

I have tried to blacklist the `wl` driver, by adding `blacklist wl` to `/etc/modprode.d/wl-blacklist.conf` and rebooting.. but that didn't change anything

I am using an XPS15 9550, it has a Broadcom BCM43692.

```
❯ sudo lshw -C Network
  *-network UNCLAIMED       
       description: Network controller
       product: BCM43602 802.11ac Wireless LAN SoC
       vendor: Broadcom Inc. and subsidiaries
       physical id: 0
       bus info: pci@0000:02:00.0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: latency=0
       resources: memory:dd800000-dd807fff memory:dd400000-dd7fffff
  *-network
       description: Ethernet interface
       product: USB 10/100/1000 LAN
       physical id: f
       bus info: usb@2:1
       logical name: enp0s20f0u1
       serial: 9c:eb:e8:1c:01:95
       size: 1Gbit/s
       capacity: 1Gbit/s
       capabilities: ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8152 driverversion=v1.12.13 duplex=full firmware=rtl8153a-2 v1 10/23/19 ip=10.0.0.129 link=yes multicast=yes port=MII speed=1Gbit/s
```

here are some boot log lines of interest

```
journalctl -b |rg  wl
Jun 08 09:18:23 xps15 kernel: wl: module license 'MIXED/Proprietary' taints kernel.
Jun 08 09:18:23 xps15 kernel: wl 0000:02:00.0: enabling device (0000 -> 0002)
Jun 08 09:18:23 xps15 kernel: wl driver 6.30.223.271 (r587334) failed with code 1
Jun 08 09:18:23 xps15 kernel: ERROR @wl_cfg80211_detach : 
Jun 08 09:18:23 xps15 kernel: NULL ndev->ieee80211ptr, unable to deref wl
Jun 08 09:18:24 xps15 NetworkManager[915]: <info>  [1686212304.4791] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 20-connectivity-fedora.conf, 90-broadcom-wl.conf)
```

not sure what other information would be useful, please let me know if you'd like to see more and I will add here.

Could anyone suggest a way to get my wifi working again?

**Comment by EyeCantCU** [comment] 2023-06-08 13:45
Hi,

I'm happy to help with this. Try removing (after backing up) `/usr/lib/modprobe.d/broadcom-wl-blacklist.conf` as this unloads the drivers for newer bc wireless cards and keep wl blacklisted

**Comment by EyeCantCU** [comment] 2023-06-09 11:23
Yup, you're right. I think the file gets copied over to /etc/modprobe.d as well if you want to try that

Otherwise, give this a go:

```
sudo rmmod wl
sudo modprobe bcma
sudo modprobe brcmsmac
```

**Comment by bugthing** [comment] 2023-06-09 11:47
there was no copy of `/usr/lib/modprobe.d/broadcom-wl-blacklist.conf` in `/etc/modprobe.d` so i created it and commented out the `b43` and `ssb`.. this seemed to make no difference.
I then tried the 3 commands suggested... still no change.
thanks again for you help.. once the revert goes in I guess that gets things back how they were (broadcom driver wise), so hopefully it will start to work again :crossed_fingers:

**Comment by EyeCantCU** [comment] 2023-06-09 11:52
Yeah. The issue is (according to the documentation of the kmod) the drivers conflict. As soon as that revert gets merged and akmods get rebuilt, you'll be fine. Happy to help out

**Closed** 2023-06-13 19:58 UTC
